name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Start Test Marker
        run: echo "RUN CODEI TESTS"

      - name: Run Tests
        run: pytest

      - name: End Test Marker
        run: echo "CODEI TESTS COMPLETE"
        if: always()